name: Pull Changes
on: [push]
jobs:
  pull-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SECRET_KEY }}
      - name: Pull Changes
        run: |
          pwd
          git pull origin main
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install Composer Dependencies
        run: |
          cd vocaject_api
          composer install
      - name: Run Database Migrations
        run: |
          cd vocaject_api
          php artisan migrate