name: Pull Changes
on: [push]
jobs:
  pull-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SECRET_KEY }}
      - run: "bash -s" < deploy.sh