name: Pull Changes
on: push
jobs:
  pull-changes:
  runs-on: ubuntu-latest
  steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - run: git pull origin main
    - run: php artisan migrate