name: Pull Changes
on: [push]
jobs:
  pull-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup SSH Agent
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }},
          user: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: 22,
          script: |
            cd /home/zulfahmi/vocaject_api
            git pull origin main
            php artisan migrate